name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Download dependencies
      run: go mod download

    - name: Run unit tests
      run: go test -v -race ./pkg/migrator -run "TestMigrationOptions|TestOperation|TestMigration|TestAppliedMigration|TestGetFileSHA256|TestGetSlice"

    - name: Run integration tests
      env:
        INTEGRATION_TEST: "true"
      run: go test -v -race ./pkg/migrator -run "TestIntegration|TestOperationsIntegration"
      timeout-minutes: 10

    - name: Build examples
      run: go build -v ./examples/...

    - name: Build CLI tool
      run: go build -v ./cmd/migrator 